### ISSUE TITLE
make test failures with Ovmf x64

### ISSUE THREAD

**Issue by leiflindholm** [rhinstaller/efivar#13]
With an Ovmf x64 build from 4123bd7bf7c70998353b187b593dc992e0dcb146, 
under Debian Jessie (freshly updated today). Logs generated with 'strace -o <file> -s 2048 ./tester', running as root.
Tests fail both with efivarfs mounted and not mounted, but differently at least in the case of the current efivars master.

efivars-0.15-debian, efivarfs _not_ mounted
https://gist.github.com/leiflindholm/020ae403d5d710e3ac99

efivars d774e3699db4d04c72cf92e53c8161e9ac7ce2e2, efivarfs _not_ mounted
https://gist.github.com/leiflindholm/9154cd0497304fb1bb84

efivars-0.15-debian, efivarfs mounted
https://gist.github.com/leiflindholm/4afea5e6b6707f6bc4a8

efivars d774e3699db4d04c72cf92e53c8161e9ac7ce2e2, efivarfs mounted
https://gist.github.com/leiflindholm/5b1bc9159371296990ab

**Comment by vathpela** [comment]
Fixed in 510b861
