### ISSUE TITLE
Adding a statically compiled efivar

### ISSUE THREAD

**Issue by ao2** [rhinstaller/efivar#14]
Hi, I wanted to run efivar on an x86 android installation and I managed to do that by building a static binary.

Here is a patch which adds the compilation of an efivar-static executable:
http://ao2.it/tmp/add-efivar-static.patch

The patch contains two separate commits, please apply it with ```git am```, the first commit contains some Makefile cleanups.

Thanks,
   Antonio

**Comment by ao2** [comment]
Hi, any news on this? The changes are pretty straightforward.

If applying them with ```git am``` is a problem I can send a pull request.

**Comment by vathpela** [comment]
Hey, I went a slightly different way with the patch for this, but the result is similar - doing "make efivar-static" in the top level directory should get you src/efivar-static now.

**Comment by ao2** [comment]
@vathpela thanks, your solution is simpler and up to the job indeed.

I rebased the first patch in the series, the one about the Makefiles cleanups, if you want to apply it here it is:
http://ao2.it/tmp/0001-efivar-Remove-unneeded-double-colons-in-Makefiles.patch
