### ISSUE TITLE
export.c:22:19: fatal error: uchar.h: No such file or directory

### ISSUE THREAD

**Issue by mmokrejs** [rhinstaller/efivar#18]
Hi,
  I tried to compile the current snapshot (fetched) but it fails on Debian wiht:

<pre>
gcc -O0 -g -Wall -Wsign-compare -std=gnu11 -fshort-wchar -fPIC -fvisibility=hidden -D_GNU_SOURCE -I/root/efivar-master/src/include/efivar/  -Wmaybe-uninitialized  -c -o export.o export.c
export.c:22:19: fatal error: uchar.h: No such file or directory
compilation terminated.
make[1]: *** [export.o] Error 1
make[1]: Leaving directory `/root/efivar-master/src'
$ find . -name uchar.h
$
</pre>

**Comment by vathpela** [comment]
You appear not to have the development libraries for glibc installed?  You will need them.

**Comment by mmokrejs** [comment]
No, this is a Gentoo linux which compiled everything from scratch. My compiler, glibc and whole toolchain works well.
# find /usr/include -name uchar.h
/usr/include/uchar.h
/usr/include/unicode/uchar.h
#

**Comment by vathpela** [comment]
Okay, regardless of it's on gentoo or debian (you've said each now), there's nothing on the gcc command line that says not to include standard library paths, and uchar.h seems to be in /usr/include where it's expected - is gcc configured not to use that path or something?

**Comment by vathpela** [comment]
I'm closing this issue as the requested information has not been provided.  If you're still experiencing a problem, feel free to re-open it with more information.
