### ISSUE TITLE
Cannot build from fresh clone

### ISSUE THREAD

**Issue by wmertens** [rhinstaller/efivar#19]
When building, the efivar-guids.h is missing from /usr/include and the Makefile doesn't make it. Manually cd'ing into src/ and running `make include/efivar/efivar-guids.h` doesn't work either because of -ldl being a make dependency.

It seems to me that efivar-guids.h should be made before a build and should not use the system one since it will be a previous version.

**Comment by vathpela** [comment]
Can you show me the exact error when you run "make clean all" from the top-level directory?  My suspicion is that means there's a stale gcc dep file (.foo.c.P or similar), or we're missing one in the Makefile.

**Comment by vathpela** [comment]
This should be fixed in 25d14cbd3512b0f2a73ec4d179fd35e169db44d4 .
