### ISSUE TITLE
efibootmgr --unicode option fails with "Invalid argument" error

### ISSUE THREAD

**Issue by nickchalk** [rhinstaller/efivar#22]
When attempting to add a new boot entry with efibootmgr, and passing extra command line arguments with the `--unicode` option, the operation fails with an "Invalid argument" error.

For example:

    # efibootmgr -c -d /dev/sdc -p 1 -L 'Debian' -l '\efi\debian\vmlinuz.efi' --unicode 'root=/dev/sdc2 ro initrd=\efi\debian\initrd.img'
    efibootmgr: Could not set variable: Invalid argument
    efibootmgr: Could not prepare boot variable: Invalid argument

The problem was first noticed with the Debian unstable packages, but reproduced with efibootmgr v0.12 and efivar v0.20 tarballs downloaded from GitHub.

A little digging suggests that the problem is over-zealous call validation in efivar's `efi_loadopt_create()`. On line 39 of `loadopt.c`, there is a test of the call parameters:

    if (!description || (!optional_data && optional_data_size != 0))

However, in efibootmgr's `make_boot_var()`, there is a call:

    needed = make_linux_load_option(&boot->data, &boot->data_size, NULL, sz);

which results in `efi_loadopt_create()` being called with `optional_data` == NULL and `optional_data_size` != 0 when the `-u` option is used. The call appears to be correct, as `make_boot_var()` uses the returned value to allocate a buffer for a later call.

Removing the tests on `optional_data` and `optional_data_size` allows the new boot entry operation to complete.

(Adding the new boot entry to the boot order also fails - I have yet to investigate that problem.)

Nick.

**Comment by benjarobin** [comment]
Sorry did not see that the analyses was already done... The pull request is here https://github.com/rhinstaller/efivar/pull/27

**Comment by vathpela** [comment]
I've fixed this in a very slightly different way in d07807c80cffa32460c10ddb0f76ac49d9c00387 - still doing that check, but correctly doing it /after/ we check if it's just evaluating what size of allocation we should do.

**Comment by benjarobin** [comment]
The check `if (!dp && dp_size == 0) {` is wrong
If `dp_size = 1` and `dp` is NULL => Crash

Furthermore memcpy doesn't allow the 1st and the 2nd to be NULL. You should protect against this case even if dp_size = 0, otherwise static analyses are not happy

**Comment by benjarobin** [comment]
In my pull request I forget to check that buf is not NULL, a check should also be added...
