### ISSUE TITLE
Quality Assurance issue

### ISSUE THREAD

**Issue by toralf** [rhinstaller/efivar#30]
Hello,

a Quality Assurance issue was reported by the build system of my Gentoo Linux tinderbox [1] while building a Gentoo package containing your software.

Such reported issues are sometimes correct.
Otherwise just drop this mail.
OTOH it would be interesting why the issue is wrong.

QA: other
QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.
dp-media.c:37:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
dp-message.c:577:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
dp-message.c:578:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
dp-message.c:585:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
dp-message.c:586:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
Please do not file a Gentoo bug and instead report the above QA
issues directly to the upstream developers of this software.
Homepage: https://github.com/rhinstaller/efivar

**Comment by vathpela** [comment]
This is the same issue as https://github.com/rhinstaller/efivar/issues/25 , and should be fixed in https://github.com/rhinstaller/efivar/commit/904ffda172d5037356b00ae956c450d12c7b35f4
