### ISSUE TITLE
The file path inside the EFI variable "fwupdate-xxxx" is created incorrectly. 

### ISSUE THREAD

**Issue by jiazhang0** [rhinstaller/efivar#34]
To reproduce this issue, please follow these steps.

1. Create 2 partitions on a USB key or SSD
* The first partition is FAT (/dev/sda1), with the following layout:
```
/EFI
  + boot/
  + bootx64.efi
  + <dir>/ //<dir> is controlled by fwupdate during build time
    + fw/
    + fwupdate.efi
```
* The second partition is EXT3/4 (/dev/sda2) and rootfs is in it.
- Boot the Linux kernel with the following kernel commands:
```
root=/dev/sda2 rw rootwait
```
- Login to Linux system. Run the following commands:
```
$ mkdir /boot/efi
$ mount /dev/sda1 /boot/efi
$ fwupdmgr install firmware.cab
$ cd /sys/firmware/efi/efivars
$ hexdump -C fwupdate-*
```

The dumped file path contains an invalid file path.

The attached patch for efivar explains why this issue happens. For example, if /dev/sda1 has been mounted at another place prior to running "mount /dev/sda1 /boot/efi", e.g, /media/sda1, then the generated file path in fwupdate-* variable (and the BootXXXX variable which contains the path to fwupdate.efi) will be corrupted.

Note: if /dev/sda1 has been mounted at /boot/efi, please manually umount it and then mount it to /media/sda1 then mount it again at /boot/efi.

The patch is attached:
```C
From 8bd7845e95baf2d5e1b296cca2718426d8f4e120 Mon Sep 17 00:00:00 2001
From: Lans Zhang <jia.zhang@windriver.com>
Date: Sat, 26 Sep 2015 14:00:04 +0800
Subject: [PATCH] Fix getting back a wrong relpath

If a device is mounted at morn than one mount points, the relpath
may be created with unexpected result because there is no compare
before doing it.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
---
 src/creator.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/creator.c b/src/creator.c
index 1244cb8..c33b935 100644
--- a/src/creator.c
+++ b/src/creator.c
@@ -116,6 +116,8 @@ find_file(const char * const filepath, char **devicep, char **relpathp)
 				errno = ENAMETOOLONG;
 				goto err;
 			}
+			if (strncmp(linkbuf, me->mnt_dir, mntlen))
+				continue;
 			*devicep = strdup(me->mnt_fsname);
 			if (!*devicep)
 				goto err;
-- 
1.9.1
```

**Comment by jiazhang0** [comment]
### This is an h3 tag

**Comment by vathpela** [comment]
(In the future, if you'd make the patch a pull request instead of just attached to the issue, that makes things much easier.)
