### ISSUE TITLE
Compilation with CLANG

### ISSUE THREAD

**Issue by gbetous** [rhinstaller/efivar#45]
Hi,

We are working on compiling efivar on CLANG (for Android-N). We are facing an issue with the variable argument handling in efi_set_variable() as CLANG does not support __builtin_va_arg_pack functions.

What do you suggest as a definitive fix ?

We can provide a patch either 
- fixes the optional parameter as mandatory, which will break the compatibility for some code
- with some #ifdef code suppress the handling of this parameter in CLANG (and can show eventual warning)

Thank you for your suggestion,

Regards,

**Comment by vathpela** [comment]
I suspect https://github.com/rhinstaller/efivar/commit/975356c9486ff7fa0ec5534ef56cc6f519ad11b4 actually fixes your issue anyway?

**Comment by gbetous** [comment]
oh yes, it seems I'm not up to date !

Thanks :)
