### ISSUE TITLE
Fix build with kernel 4.x

### ISSUE THREAD

**Issue by tpgxyz** [rhinstaller/efivar#48]
Hi,

Please adopt this patch
https://github.com/OpenMandrivaAssociation/efivar/blob/master/efivar-0.23-kernel-4.x.patch

**Comment by vathpela** [comment]
I think this is obviated by 8910f45c27fadba0904f707e7c40ad80bf828f7e , so I'm closing this.  Feel free to reopen if that doesn't work for you.
