### ISSUE TITLE
NVMe EUI parsing from sysfs is still wrong with 30 release

### ISSUE THREAD

**Issue by superm1** [rhinstaller/efivar#65]
As mentioned in https://github.com/rhinstaller/efibootmgr/issues/48#issuecomment-251494618 the EUI path is still wrong (or perhaps it was kernel dependent and changed?)

It should actually be: `/sys/class/block/nvme%dn%d/eui`.

**Comment by vathpela** [comment]
Yeah, looks like https://github.com/torvalds/linux/commit/779ff75617099f4defe14e20443b95019a4c5ae8 moved it.  *sigh*.
