### ISSUE TITLE
Make fails: /usr/bin/ld: cannot find -lpopt

### ISSUE THREAD

**Issue by The-Loud** [rhinstaller/efivar#72]
Currently working on building an LFS system that will boot UEFI. I've installed the popt-1.16 file as listed in the book: http://www.linuxfromscratch.org/blfs/view/cvs/general/popt.html

I've also been following this guide:http://www.linuxfromscratch.org/hints/downloads/files/lfs-uefi.txt

Namely the following commands:
Compile the package:
        sed 's|-O0|-Os|g' -i Make.defaults
        sed 's|-rpath=$(TOPDIR)/src/|-rpath=$(libdir)|g' \
             -i src/test/Makefile
        make libdir="/usr/lib/" bindir="/usr/bin/" \
             mandir="/usr/share/man/"     \
             includedir="/usr/include/" V=1 -j1

however it fails at:

root:/sources/efivar# 
make libdir="/usr/lib/" bindir="/usr/bin/" \
              mandir="/usr/share/man/"     \
              includedir="/usr/include/" V=1 -j1

make[1]: Entering directory '/sources/efivar/src'
make -f /sources/efivar/src/Make.deps deps SOURCES="crc32.c creator.c disk.c gpt.c linux.c loadopt.c dp.c dp-acpi.c dp-hw.c dp-media.c dp-message.c efivarfs.c error.c export.c guid.c guids.S guid-symbols.c lib.c vars.c makeguids.c guid.c include/efivar/efivar-guids.h include/efivar/efivar.h include/efivar/efiboot.h include/efivar/efiboot-loadopt.h include/efivar/efivar-dp.h include/efivar/efiboot-creator.h include/efivar/efivar-guids.h guid-symbols.c efivar.c"
make[2]: Entering directory '/sources/efivar/src'
make[2]: Nothing to be done for 'deps'.
make[2]: Leaving directory '/sources/efivar/src'
gcc -O2 -flto -g3 -I/sources/efivar/src/include/efivar/  -specs=/sources/efivar/gcc.specs  -L.      -static  -o efivar-static efivar.c dp.static.o dp-acpi.static.o dp-hw.static.o dp-media.static.o dp-message.static.o efivarfs.static.o error.static.o export.static.o guid.static.o guids.static.o guid-symbols.static.o lib.static.o vars.static.o -ldl -lpopt
/usr/bin/ld: cannot find -lpopt
collect2: error: ld returned 1 exit status
make[1]: **\* [/sources/efivar/Make.rules:17: efivar-static] Error 1
make[1]: Leaving directory '/sources/efivar/src'
make: **\* [Makefile:11: all] Error 2

So i've never even run the:

  Install the package:
        make -j1 V=1 DESTDIR="${pkgdir}/" libdir="/usr/lib/" \
        bindir="/usr/bin/" mandir="/usr/share/man"   \
        includedir="/usr/include/" install

```
  install -v -D -m0755 src/test/tester /usr/bin/efivar-tester
```

Below I've confimed these exist:

root:/sources/efivar# ls /usr/lib64 | grep libpopt.so
libpopt.so
libpopt.so.0
libpopt.so.0.0.0

**Comment by judu** [comment]
I hit the same wall last night, and after some digging, it seems that some "distros" disabled static libraries in their popt packages. (I'm using exherbo, but [LFS did the same, apparently](http://stackoverflow.com/questions/40319604/efivar-cannot-find-lpopt).) I don't know why, I didn't asked.

On exherbo, I disabled the production of efivar-static: [0001-Fix-build-disable-efivar-static-build.txt](https://github.com/rhinstaller/efivar/files/721373/0001-Fix-build-disable-efivar-static-build.txt). Don't throw the stone yet, it was 4am already and I was having a hard time with boot issues. :D

**Comment by vathpela** [comment]
I've disabled building efivar-static by default and added a top level build target named "static".  So if previously you were doing:```
make all install
``` and you still want the same result, you'll need to do ```
make all static install```
