### ISSUE TITLE
Where's the overload for "the optional mode parameter" for efi_set_variable?

### ISSUE THREAD

**Issue by sippeangelo** [rhinstaller/efivar#73]
The man page talks about an overload for `efi_set_variable` where the `mode` is optional. Why is this missing from the library? I'd love to be able to set variables without arbitrarily changing file modes around, or at least have an option where the file mode only applies to new variables and isn't changed if the variable already exists.

[docs/efi_get_variable.3#L72](https://github.com/rhinstaller/efivar/blob/91660d700e4b2d289da2b8a2c35f8d3cea3b4071/docs/efi_get_variable.3#L72)
[docs/efi_get_variable.3#L27](https://github.com/rhinstaller/efivar/blob/91660d700e4b2d289da2b8a2c35f8d3cea3b4071/docs/efi_get_variable.3#L27)

**Comment by vathpela** [comment]
Unfortunately we had to take that out because keeping the linker happy with 2 definitions turns out to be incredibly painful, and we simply forgot to update the docs.  I've done that now in 4269b660edba2406cdd1080b2c4073f5bb977168 . Sorry.

Using 0644 should always be safe.
