### ISSUE TITLE
Build with uClibc

### ISSUE THREAD

**Issue by andy-shev** [rhinstaller/efivar#76]
At least efivar can be built in uClibc environment. I have a patch: https://github.com/andy-shev/efivar/commit/2255601757a8a58baddad2d37d0bcc6b003a3732

**Comment by gordio** [comment]
Nice. This patch can help me!
```
x86_64-gentoo-linux-uclibc-gcc -march=broadwell -O2 -pipe -flto -I/var/tmp/portage/sys-libs/efivar-30/work/efivar-30/src/include/efivar/  -specs=/var/tmp/portage/sys-libs/efivar-30/work/efivar-30/gcc.specs  -fPIC  -c -o export.o export.c
export.c:24:19: fatal error: uchar.h: No such file or directory
compilation terminated.
```

**Comment by vathpela** [comment]
I guess it's reasonable to ship this patch in the distro packaging if your distro supports using uClibc.  From an upstream perspective, uClibc really needs to be providing modern C headers. Changing every program to hack around a toolchain that's incomplete simply isn't a sustainable plan.

**Comment by andy-shev** [comment]
TWIMC, from February 2017 uClibc-NG has that header. uClibc on the other hand seems abandoned.
