### ISSUE TITLE
ABI tracker for libefivar and libefiboot

### ISSUE THREAD

**Issue by lvc** [rhinstaller/efivar#77]
Hello,

I've set up a tracker of API/ABI changes for the efivar base libraries here: https://abi-laboratory.pro/tracker/timeline/efivar/

It's based on the open-source tools:

https://github.com/lvc/abi-tracker
https://github.com/lvc/abi-compliance-checker

Hope it will be helpful for users and maintainers of the library.

Thank you.

**Comment by vathpela** [comment]
This is great, thanks!
